version: "2"

linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - gochecknoinits
    - gocritic
    - gosec
    - govet
    - importas
    - misspell
    - nakedret
    - nilerr
    - noctx
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - unlambda
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters: [gosec]
        text: "G101"
        path: _test\.go
    paths:
      - _legacy$

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
