apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - hpa.yaml
  - pdb.yaml

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: ghcr.io/oakwood-commons/event-reactor
    newTag: v1.0.0
